export const CONSONANTS: Record<string, { initial: string; final: string }> = {
  'ก': { initial: 'k', final: 'k' },
  'ข': { initial: 'kh', final: 'k' },
  'ฃ': { initial: 'kh', final: 'k' },
  'ค': { initial: 'kh', final: 'k' },
  'ฅ': { initial: 'kh', final: 'k' },
  'ฆ': { initial: 'kh', final: 'k' },
  'ง': { initial: 'ng', final: 'ng' },
  'จ': { initial: 'ch', final: 't' },
  'ฉ': { initial: 'ch', final: 't' },
  'ช': { initial: 'ch', final: 't' },
  'ซ': { initial: 's', final: 't' },
  'ฌ': { initial: 'ch', final: 't' },
  'ญ': { initial: 'y', final: 'n' },
  'ฎ': { initial: 'd', final: 't' },
  'ฏ': { initial: 't', final: 't' },
  'ฐ': { initial: 'th', final: 't' },
  'ฑ': { initial: 'th', final: 't' },
  'ฒ': { initial: 'th', final: 't' },
  'ณ': { initial: 'n', final: 'n' },
  'ด': { initial: 'd', final: 't' },
  'ต': { initial: 't', final: 't' },
  'ถ': { initial: 'th', final: 't' },
  'ท': { initial: 'th', final: 't' },
  'ธ': { initial: 'th', final: 't' },
  'น': { initial: 'n', final: 'n' },
  'บ': { initial: 'b', final: 'p' },
  'ป': { initial: 'p', final: 'p' },
  'ผ': { initial: 'ph', final: 'p' },
  'ฝ': { initial: 'f', final: 'p' },
  'พ': { initial: 'ph', final: 'p' },
  'ฟ': { initial: 'f', final: 'p' },
  'ภ': { initial: 'ph', final: 'p' },
  'ม': { initial: 'm', final: 'm' },
  'ย': { initial: 'y', final: '' },
  'ร': { initial: 'r', final: 'n' },
  'ฤ': { initial: 'rue', final: '' },
  'ล': { initial: 'l', final: 'n' },
  'ว': { initial: 'w', final: '' },
  'ศ': { initial: 's', final: 't' },
  'ษ': { initial: 's', final: 't' },
  'ส': { initial: 's', final: 't' },
  'ห': { initial: 'h', final: '' },
  'ฬ': { initial: 'l', final: 'n' },
  'อ': { initial: '', final: '' },
  'ฮ': { initial: 'h', final: '' },
};

export const VOWELS: Record<string, string> = {
  'ะ': 'a',
  'ั': 'a',
  'า': 'a',
  'ิ': 'i',
  'ี': 'i',
  'ึ': 'ue',
  'ื': 'ue',
  'ุ': 'u',
  'ู': 'u',
  'เ': 'e',
  'แ': 'ae',
  'โ': 'o',
  'อ': 'o',
  'เ-อะ': 'oe',
  'เ-อ': 'oe',
  'เ-ีย': 'ia',
  'เ-ือ': 'uea',
  'ัว': 'ua',
  'ใ': 'ai',
  'ไ': 'ai',
  'ำ': 'am',
};

export const TONE_MARKS = ['่', '้', '๊', '๋'];
export const SILENT_MARK = '์';
