/**
 * Full province name romanization (RTGS-style, no spaces).
 * Checked before syllable segmentation — same pattern as loanwords.
 */
export const PROVINCE_ROMAN: Record<string, string> = {
    'กระบี่': 'krabi',
    'กาญจนบุรี': 'kanchanaburi',
    'กาฬสินธุ์': 'kalasin',
    'กำแพงเพชร': 'kamphaengphet',
    'ขอนแก่น': 'khonkaen',
    'จันทบุรี': 'chanthaburi',
    'ฉะเชิงเทรา': 'chachoengsao',
    'ชลบุรี': 'chonburi',
    'ชัยนาท': 'chainat',
    'ชัยภูมิ': 'chaiphum',
    'ชุมพร': 'chumphon',
    'ตรัง': 'trang',
    'ตาก': 'tak',
    'ตราด': 'trat',
    'นครนายก': 'nakhonnayok',
    'นครปฐม': 'nakhonpathom',
    'นครพนม': 'nakhonphanom',
    'นครราชสีมา': 'nakhonratchasima',
    'นครศรีธรรมราช': 'nakhonsithammarat',
    'นครสวรรค์': 'nakhonsawan',
    'นนทบุรี': 'nonthaburi',
    'นราธิวาส': 'narathiwat',
    'น่าน': 'nan',
    'บึงกาฬ': 'buengkan',
    'บุรีรัมย์': 'buriram',
    'ปทุมธานี': 'pathumthani',
    'ประจวบคีรีขันธ์': 'prachuapkhirikhan',
    'ปราจีนบุรี': 'prachinburi',
    'ปัตตานี': 'pattani',
    'พระนครศรีอยุธยา': 'phranakhonsiayutthaya',
    'พะเยา': 'phayao',
    'พังงา': 'phangnga',
    'พัทลุง': 'phatthalung',
    'พิจิตร': 'phichit',
    'พิษณุโลก': 'phitsanulok',
    'ภูเก็ต': 'phuket',
    'มหาสารคาม': 'mahasarakham',
    'แม่ฮ่องสอน': 'maehongson',
    'ยโสธร': 'yasothon',
    'ยะลา': 'yala',
    'ร้อยเอ็ด': 'roiet',
    'ระนอง': 'ranong',
    'ระยอง': 'rayong',
    'ราชบุรี': 'ratchaburi',
    'ลพบุรี': 'lopburi',
    'ลำปาง': 'lampang',
    'ลำพูน': 'lamphun',
    'ศรีสะเกษ': 'sisaket',
    'สกลนคร': 'sakonnakhon',
    'สงขลา': 'songkhla',
    'สตูล': 'satun',
    'สมุทรปราการ': 'samutprakan',
    'สมุทรสงคราม': 'samutsongkhram',
    'สมุทรสาคร': 'samutsakhon',
    'สระแก้ว': 'sakaew',
    'สระบุรี': 'saraburi',
    'สิงห์บุรี': 'singburi',
    'สุโขทัย': 'sukhothai',
    'สุพรรณบุรี': 'suphanburi',
    'สุราษฎร์ธานี': 'suratthani',
    'สุรินทร์': 'surin',
    'หนองคาย': 'nongkhai',
    'หนองบัวลำภู': 'nongbualamphu',
    'อ่างทอง': 'angthong',
    'อำนาจเจริญ': 'amnatcharoen',
    'อุดรธานี': 'udonthani',
    'อุตรดิตถ์': 'uttaradit',
    'อุทัยธานี': 'uthaithani',
    'อุบลราชธานี': 'ubonratchathani',
    'เชียงราย': 'chiangrai',
    'เชียงใหม่': 'chiangmai',
    'เพชรบุรี': 'phetchaburi',
    'เพชรบูรณ์': 'phetchabun',
    'เลย': 'loei',
    'แพร่': 'phrae',
    'มุกดาหาร': 'mukdahan',
};

export function romanizeProvince(text: string): string | null {
    return PROVINCE_ROMAN[text] ?? null;
}
